name: 🧪 Parallel Coverage Tests

on:
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug
          extensions: fileinfo
      - uses: actions/checkout@v4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set environment to testing
        run: echo "ENV=testing" > .env

      - name: Prepare test directories
        run: |
          mkdir unit_tests feature_tests
          cp -R . unit_tests/
          cp -R . feature_tests/

      - name: Execute Unit Tests
        run: |
          cd unit_tests
          vendor/bin/pest --coverage --coverage-clover ../unit-clover.xml --log-junit ../unit-report.xml tests/Unit

      - name: Execute Feature Tests
        run: |
          cd feature_tests
          vendor/bin/pest --coverage --coverage-clover ../feature-clover.xml --log-junit ../feature-report.xml tests/Feature

      - name: Install phpcov
        run: composer global require phpunit/phpcov

      - name: Merge coverage reports
        run: phpcov merge --clover merged-clover.xml unit-clover.xml feature-clover.xml

      - name: "Publish coverage report to Codecov"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./merged-clover.xml

      - name: Ping statistics server with test results
        run: |
          curl https://raw.githubusercontent.com/hydephp/develop/6e9d17f31879f4ccda13a3fec4029c9663bccec0/monorepo/scripts/ping-openanalytics-testrunner.php -o ping.php
          php ping.php "Monorepo Coverage Tests" ${{ secrets.OPENANALYTICS_TOKEN }} ${{ github.ref_name }}
