name: 🧪 Parallel Coverage Tests

on:
  pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: xdebug
          extensions: fileinfo

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: src/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: |
          cd src
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set environment to testing
        run: |
          cd src
          echo "ENV=testing" > .env

      - name: Prepare test directories
        run: |
          cp -R src unit_tests
          cp -R src feature_tests

      - name: Execute Tests in Parallel
        run: |
          mkdir -p coverage
          # Start unit tests in the background
          (
            cd unit_tests
            vendor/bin/pest --colors=always --coverage-php=../coverage/unit.cov --log-junit=../coverage/unit.junit.xml --testsuite=UnitFramework 2>&1 | sed -E $'s/^/\x1b[36m[UNIT]   \x1b[0m /' &
          ) &
          # Start feature tests in the background
          (
            cd feature_tests
            vendor/bin/pest --colors=always --coverage-php=../coverage/feature.cov --log-junit=../coverage/feature.junit.xml --testsuite=FeatureHyde,FeatureFramework,Publications,"Realtime Compiler" 2>&1 | sed -E $'s/^/\x1b[35m[FEATURE]\x1b[0m /' &
          ) &
          
          # Wait for both background processes to finish
          wait

      - name: Download phpcov
        run: wget https://phar.phpunit.de/phpcov.phar

      - name: Merge coverage reports
        run: |
          php phpcov.phar merge --clover=coverage.xml coverage
          cp coverage.xml coverage/

      - name: Merge JUnit XML reports
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > report.xml
          echo '<testsuites>' >> report.xml
          sed -n '/<testsuite/,/<\/testsuite>/p' coverage/unit.junit.xml >> report.xml
          sed -n '/<testsuite/,/<\/testsuite>/p' coverage/feature.junit.xml >> report.xml
          echo '</testsuites>' >> report.xml

      - name: "Publish coverage report to Codecov"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Ping statistics server with test results
        run: |
          curl https://raw.githubusercontent.com/hydephp/develop/6e9d17f31879f4ccda13a3fec4029c9663bccec0/monorepo/scripts/ping-openanalytics-testrunner.php -o ping.php
          php ping.php "Monorepo Coverage Tests" ${{ secrets.OPENANALYTICS_TOKEN }} ${{ github.ref_name }}
