name: Deploy Documentation Preview

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docs/**'

jobs:

  build-documentation-preview:
    environment:
      name: pr-documentation-${{ github.event.pull_request.number }}
      url: https://hydephp.github.io/develop/pr-${{ github.event.pull_request.number }}/dev-docs-preview

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@16011a795d747d5f45038f96371c3b98aec5669d
        with:
          php-version: "8.1"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Download configuration
        run: wget https://api.github.com/repos/hydephp/develop/zipball/gh-pages-config-dev-docs -O config.zip

      - name: Unzip configuration
        run: unzip config.zip -d temp

      - name: Copy configuration to root
        run: cp -r temp/hydephp-develop-*/* .

      - name: Update config to load styles from CDN
        run: sed -i "s/'load_app_styles_from_cdn' => false/'load_app_styles_from_cdn' => true/g" config/hyde.php

      - name: Move documentation files
        run: rm -rf _docs && mv -f docs _docs

      - name: Compile the static site
        run: php hyde build

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: 'preview-docs'
          path: '_site/dev-docs'


  upload-generated-site:

    runs-on: ubuntu-latest
    needs:
      - build-documentation-preview

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      - name: Reset output directories
        run: |
          rm -rf pr-${{ github.event.pull_request.number }}/dev-docs-preview
          mkdir -p pr-${{ github.event.pull_request.number }}/dev-docs-preview

      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: preview-docs
          path: pr-${{ github.event.pull_request.number }}/dev-docs-preview

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pr-${{ github.event.pull_request.number }}/dev-docs-preview'
          message: 'Upload documentation preview for PR #${{ github.event.pull_request.number }}'
