name: Deploy Documentation Preview

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - 'docs/**'

jobs:

  build-documentation-preview:
    environment:
      name: pr-documentation-${{ github.event.pull_request.number }}
      url: https://hydephp.github.io/develop/pr-${{ github.event.pull_request.number }}/dev-docs-preview

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@16011a795d747d5f45038f96371c3b98aec5669d
        with:
          php-version: "8.1"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Download configuration
        run: wget https://api.github.com/repos/hydephp/develop/zipball/gh-pages-config-dev-docs -O config.zip

      - name: Unzip configuration
        run: unzip config.zip -d temp

      - name: Copy configuration to root
        run: cp -r temp/hydephp-develop-*/* .

      - name: Update configuration files
        run: |
          sed -i "s/'use_play_cdn' => false/'use_play_cdn' => true/g" config/hyde.php
          sed -i "s/'output_directory' => 'dev-docs'/'output_directory' => 'dev-docs-preview'/g" config/docs.php
          sed -i "s/'header_title' => config('site.name', 'HydePHP').' Docs'/'header_title' => 'PR #${{ github.event.pull_request.number }} - Docs'/g" config/docs.php

      - name: Remove published article component
        run: rm resources/views/vendor/hyde/components/docs/documentation-article.blade.php

      - name: Create component to add an information badge
        run: |
          mkdir -p resources/views/vendor/hyde/layouts
          cp vendor/hyde/framework/resources/views/layouts/docs.blade.php resources/views/vendor/hyde/layouts/docs.blade.php
          cat <<- HTML >> resources/views/vendor/hyde/layouts/docs.blade.php
            <aside class="fixed bottom-4 right-4 z-50 hidden md:block">
              <div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-4">
                <h3 class="text-lg font-bold mb-2">Documentation preview for <a href="https://github.com/hydephp/develop/pull/${{ github.event.pull_request.number }}" class="dark:text-indigo-400 text-indigo-500 hover:text-indigo-600">PR #${{ github.event.pull_request.number }}</a></h3>
                <p class="text-gray-600 dark:text-gray-400 prose">
                  You are browsing the documentation for a <code>hydephp/develop</code> pull request to <code>${{ github.event.pull_request.head.ref }}</code> branch.<br>
                  This page was generated for commit <code>${{ github.event.pull_request.head.sha }}</code> on pull request <code>${{ github.event.pull_request.number }}</code>.
                  <a href="${{ github.event.pull_request.html_url }}" class="dark:text-indigo-400 text-indigo-500 hover:text-indigo-600">Back to PR</a>
                </p>
              </div>
            </aside>
          
            <!-- Hotpatch for https://github.com/hydephp/develop/issues/968 -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/hydephp/develop@master/_media/app.css">
          HTML

      - name: Configure environment variables
        run: |
          echo 'SITE_NAME="HydePHP Documentation Preview"' >> .env
          echo 'SITE_URL="https://hydephp.github.io/develop/pr-${{ github.event.pull_request.number }}/dev-docs-preview"' >> .env

      - name: Move documentation files
        run: rm -rf _docs && mv -f docs _docs

      - name: Compile the static site
        run: php hyde build

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: 'preview-docs'
          path: '_site/dev-docs-preview'


  upload-generated-site:

    runs-on: ubuntu-latest
    needs:
      - build-documentation-preview

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'

      - name: Reset output directories
        run: |
          rm -rf pr-${{ github.event.pull_request.number }}/dev-docs-preview
          mkdir -p pr-${{ github.event.pull_request.number }}/dev-docs-preview

      - name: Download documentation artifact
        uses: actions/download-artifact@v3
        with:
          name: preview-docs
          path: pr-${{ github.event.pull_request.number }}/dev-docs-preview

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pr-${{ github.event.pull_request.number }}/dev-docs-preview'
          message: 'Upload documentation preview for PR #${{ github.event.pull_request.number }}'
