name: 🔬 HydeStan

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  analyze:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Static Analysis
        run: php ./monorepo/HydeStan/run.php

      - name: Run HydeFront linter
        run: php packages/hydefront/.github/scripts/post-build.php

      - name: Run DocGen linter
        run: composer install && php monorepo/scripts/docs/DocGen.php --lint
