name: 🏷 Label Pull Requests

on:
  pull_request:
    types: [opened, edited, reopened, closed]

jobs:

  label-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: '.github/scripts'
          sparse-checkout: '.github/scripts'
          sparse-checkout-cone-mode: false

      # If PR title starts with "Internal: " then add the "Internal" label
      - name: Label Internal Pull Requests
        if: "startsWith(github.event.pull_request.title, 'Internal: ')"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/LabelInternal.js');
            console.log(script({github, context}))

      # Remove "run-visual-tests" label if the pull request is closed
      - name: Remove run-visual-tests Label
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/RemoveRunVisualTests.js');
            console.log(script({github, context}))
