name: Label Pull Requests

on:
  pull_request:

jobs:

    label-pull-requests:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          pull-requests: write

        steps:
          # Todo
