name: 🔎 Static Analysis

on:
  pull_request:
    branches: [ "master" ]

jobs:

  psalm:
    name: Run Analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      exit-code: ${{ steps.analysis.outputs.EXIT_CODE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Psalm
        id: analysis
        run: vendor/bin/psalm > psalmout.txt || echo EXIT_CODE=$? >> $GITHUB_OUTPUT || exit 0

        # Send the reports to the CI server to calculate type coverage and send back commit status checks
      - name: Ping CI server with type coverage results
        run: php monorepo/scripts/ping-ci-server-with-type-coverage.php ${{ secrets.CI_SERVER_TOKEN }} ${{ github.event.pull_request.head.sha }} ${{ github.head_ref }}
